
TRUNCATE TABLE UNCLAIMED_WORKS;

SELECT @SNAPSHOT_ID := MAX(snapshotid) FROM SNAPSHOTS;

SELECT NOW() FROM DUAL;

LOAD DATA INFILE 'unclaimedworkrightshares.tsv'
    INTO TABLE UNCLAIMED_WORKS
    FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\'
    SET snapshotid= @SNAPSHOT_ID
;


SELECT NOW() FROM DUAL;

