
TRUNCATE TABLE ALTERNATIVE_RECORDING_TITLES;

SELECT @SNAPSHOT_ID := MAX(snapshotid) FROM SNAPSHOTS;

SELECT NOW() FROM DUAL;


LOAD DATA INFILE 'recordingalternativetitles.tsv'
    INTO TABLE ALTERNATIVE_RECORDING_TITLES
    FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\'
    SET snapshotid= @SNAPSHOT_ID
;

SELECT NOW() FROM DUAL;
