
TRUNCATE TABLE WORK_RECORDINGS;

SELECT @SNAPSHOT_ID := MAX(snapshotid) FROM SNAPSHOTS;

SELECT NOW() FROM DUAL;

LOAD DATA INFILE 'worksrecordings.tsv'
    INTO TABLE WORK_RECORDINGS
    FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\'
    SET snapshotid= @SNAPSHOT_ID
;

SELECT NOW() FROM DUAL;

