
TRUNCATE TABLE ALTERNATIVE_WORK_TITLES;

SELECT @SNAPSHOT_ID := MAX(snapshotid) FROM SNAPSHOTS;

SELECT NOW() FROM DUAL;

LOAD DATA INFILE 'workalternativetitles.tsv'
    INTO TABLE ALTERNATIVE_WORK_TITLES
    FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\'
    SET snapshotid= @SNAPSHOT_ID
;

SELECT NOW() FROM DUAL;
