
TRUNCATE TABLE RECORDINGS;

SELECT @SNAPSHOT_ID := MAX(snapshotid) FROM SNAPSHOTS;


SELECT NOW() FROM DUAL;


LOAD DATA INFILE 'recordings.tsv'
    INTO TABLE RECORDINGS
    FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\'
    SET snapshotid= @SNAPSHOT_ID
;

SELECT NOW() FROM DUAL;